### ISSUE TITLE
Questions about topological formulation

### ISSUE THREAD

**Issue by LongLiveForFreedom** [OpenDriveLab/BeTop#1]
Hello, Thank you for your great work! I have some questions after reading your paper:
1. you mention that σn denotes a tuple of monotonically increased functions and the braid set σn± belongs to BNa which means the braid set should be a set of functions. However, in the figure 2 of this paper, 𝜎1+ or 𝜎1- looks like a intersection of functions but not a function. Can you explain it in detail?
2. Also in the part of Topological formulation, you mention that σn+ means assertive and σn- means passive maneuvers. How to automatically distinguish between σn+ and σn- in the process of encoding.
3. Looking forward to your public code!

**Comment by georgeliu233** [comment]
Hi, Thanks for your interest in our work.

Regarding the question of braids, 1) yes, this refers to braid interwine/crossing, which is the result from the transformation by braid function; 2) As indicated in equ.2, we considered 𝜎1+ and 𝜎1- together as 'interacted' topology. Hence, in our framework we treated them uniformly. A more intuitive understanding for this encoding process is simply to find intersections over pairs of transformed (lateral-temporal) future trajectories.

**Comment by LongLiveForFreedom** [comment]
Thank you for your reply, this makes me understand more clearly
