### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by SPA-junghokim** [OpenDriveLab/BeTop#2]
Thank you for the great work you’ve shared with the community. 
I’ve been following your research closely and am eager to dive into the code if it becomes available.

Could you let me know if there’s an expected timeline for the code release? It would be really helpful for my ongoing research.

Thx.

**Comment by georgeliu233** [comment]
Hi, thanks for your interest in our work!
We have just completed a scrutinization for prediction project, and you may expect a release in the upcoming couple of days.
